# WorkFlow Name
name: Generate engineering_blogs.opml file

# Events upon which Github WorkFlow gets triggered
on: [push, pull_request]

#Create jobs
jobs:
  generate:
    name: Generate engineering_blogs.opml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Ruby Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install pkgs
        run: |
          bundle install --jobs 4

      - name: Generate opml file using ruby
        run: |
          ruby generate_opml.rb

      - name: Auto-Commit engineering_blogs file if updated
        uses: stefanzweifel/git-auto-commit-action@v4.1.5
        with:
          commit_message: Commit by Github WorkFlow
          file_pattern: engineering_blogs.opml
